#!/usr/bin/env bash

# Define variables
REPO_URL="https://github.com/not-a-longneck/NixOS-VCVM.git"
TARGET_DIR="$HOME/nixos-config"

echo "🚀 Bootstrapping NixOS..."

# 1. Clone the repo
git clone "$REPO_URL" "$TARGET_DIR"

# 2. Copy the hardware config generated by the installer
# This ensures drive IDs and bootloaders match the current machine (VM or PC)
cp /etc/nixos/hardware-configuration.nix "$TARGET_DIR/hardware-configuration.nix"

# 3. Apply the config (change 'default' to your flake output name)
sudo nixos-rebuild boot --flake "$TARGET_DIR#default"

echo "✅ Done! Rebooting in 5 seconds..."
sleep 5
reboot
